// <auto-generated />
namespace CFDemo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renameBlogIdtoAzonosito : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renameBlogIdtoAzonosito));
        
        string IMigrationMetadata.Id
        {
            get { return "201504081349487_rename Blog.Id to Azonosito"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
