// <auto-generated />
namespace CFDemo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Titletypeinttostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Titletypeinttostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201504081257509_Title type int to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
